# Generated by Django 3.2.4 on 2021-07-02 20:21

from django.db import migrations, models
import json.decoder
import json.encoder


class Migration(migrations.Migration):

    dependencies = [
        ('abclist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abclist',
            name='abclist',
            field=models.JSONField(decoder=json.decoder.JSONDecoder, encoder=json.encoder.JSONEncoder),
        ),
    ]
